### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by chrisbenseler** [tupizz/gym_flutter_app#3]
Imagino que o app terá autenticação, né @tupizz?
Pensou em como fazer isso, se fazendo na mão no seu backend ou usandoo algum serviço de autenticação (como o Firebase, ou o Google Sign In https://pub.dev/packages/google_sign_in)?

**Comment by tupizz** [comment]
Boa, tava pensando em ser um um ser Firebase mesmo, facilitar ao máximo.
